/* GENERATED by tools/art/build-truck.mjs — DO NOT EDIT.
 * Source: SVG ART/FIRE_TRUCK.svg. Change the SVG and run `npm run art:build:truck`.
 *
 * Shape roles are assigned by document index in the build script. As exported,
 * the art is 65 drawable elements:
 *   0–13, 18–21, 27–34, 39–47  the body, ladder, glass, stripe and bumper
 *   14–17                      the door badge (disc, ring, flame glyph)
 *   22–23                      the beacon plinth
 *   24–26, 48                  the beacon dome — tinted by the child's lights
 *   35–36, 49–56               the back wheel
 *   37–38, 57–64               the front wheel
 */

/** A drawn shape, straight from the authored art. */
export interface TruckShape {
  d?: string;
  circle?: { cx: number; cy: number; r: number };
  ellipse?: { cx: number; cy: number; rx: number; ry: number };
  fill?: string;
  stroke?: string;
  strokeWidth?: number;
  strokeLinecap?: string;
  /** which part of the child's paint this shape takes, if any */
  paint?: 'face' | 'shade' | 'deep';
}

export interface TruckWheel {
  cx: number;
  cy: number;
  r: number;
  shapes: TruckShape[];
}

/** The authored drawing's own box. */
export const TRUCK_ART_VB = { w: 159.4, h: 80 } as const;

/** Everything that does not move or re-tint on its own. */
export const truckBody: TruckShape[] = [
  {
    "d": "m3 43.8c-1 0-1.8 0.8-1.9 1.9v4.9c0 1.1 0.9 1.9 1.9 1.9h0.7l-0.1-8.7h-0.6z",
    "fill": "#D60E2A",
    "paint": "deep"
  },
  {
    "d": "m93.9 20.7h-85.2c-2.8 0-5.1 2.5-5.1 5.7v33.6c0.2 1.3 1.2 2.4 2.7 2.4h90.2v-39.1c-0.2-1.5-1.3-2.6-2.6-2.6z",
    "fill": "#EA2C2F",
    "paint": "face"
  },
  {
    "d": "m3.6 53.7v6.3c0 1.3 1.2 2.4 2.5 2.4h90.4v-8.7h-92.9z",
    "fill": "#BF1C21",
    "paint": "shade"
  },
  {
    "d": "m93.9 20.7h-0.8c0.7 0.5 2.1 0.6 2.1 2.8v38.9h1.1v-39.1c0-1.5-1.1-2.6-2.4-2.6z",
    "fill": "#BF1C21",
    "paint": "shade"
  },
  {
    "d": "m27.6 27.2h-16.7c-1.5 0-2.8 1.3-2.8 3v11h22.7v-10.9c0-1.8-1.4-3.1-3.2-3.1z",
    "fill": "#BF1C21",
    "paint": "shade"
  },
  {
    "d": "m88.5 27.2h-20.4c-1.8 0-3.1 1.3-3.1 3.1v10.9h26.5v-10.9c0-1.8-1.3-3.1-3-3.1z",
    "fill": "#BF1C21",
    "paint": "shade"
  },
  {
    "d": "M3.6 41.2L3.6 48.5L96.5 48.5L96.5 41.2z",
    "fill": "#FFCD4B"
  },
  {
    "d": "m95.4 48.5h2.4l-1.3-4.4h-1.1z",
    "fill": "#FCBD2B"
  },
  {
    "d": "M3.6 44L3.6 44.1L95.4 44.1L95.4 41.2L3.6 41.2L3.6 44",
    "fill": "#FED457"
  },
  {
    "d": "m37 46.8c-7.9 0-16.9 6.1-17 15.6h33.6c-0.1-8.7-7.6-15.6-16.6-15.6z",
    "fill": "#BF1C21",
    "paint": "shade"
  },
  {
    "d": "m155.4 42c0-1.6-0.9-4-1.5-5.5l-8-18.6c-1.8-4.5-4.7-6.1-6.6-6.1h-38.8c-2.1 0-4.5 1.8-4.5 4.8v45.8h48.4l11-0.2v-20.2z",
    "fill": "#EA2C2F",
    "paint": "face"
  },
  {
    "d": "m96.5 54.4v7.7l47.9 0.3 4.8-0.2-1.1-7.8z",
    "fill": "#BF1C21",
    "paint": "shade"
  },
  {
    "d": "m122.2 46.5c-7.1 0-17.9 5.1-18 15.9h34.5c-0.3-10.8-9.3-15.9-16.5-15.9z",
    "fill": "#BF1C21",
    "paint": "shade"
  },
  {
    "d": "m88.6 9.4h-72.9c-2.4 0-4.9 2.1-4.9 4.8s2.2 5.3 4.9 5.3h72.9c2.5 0 4.7-2.1 4.7-5.1 0-2.6-2.1-5-4.7-5z",
    "fill": "#8891AD"
  },
  {
    "d": "M96.5 43.6L96.5 48.5L155.4 48.4L155.4 43.6z",
    "fill": "#FFCA37"
  },
  {
    "d": "m155 39.6c-0.6-1-1.6-1.5-2.9-1.5-2.1 0-4.4 1.5-4.4 5.4 0 2.6 1.4 4.9 4.4 4.9 1.1 0 2.4-0.4 3.3-1v-4.9c0-1.1-0.3-2.3-0.4-2.9z",
    "fill": "#FCBD2B"
  },
  {
    "d": "m149.2 41.6c-0.2 0.8 0 2 0 2.8 0.3 1.6 2.5 1.7 2.5 0.2v-4.2c0-1.3-2.1-0.7-2.5 1.2z",
    "fill": "#FFCA37"
  },
  {
    "d": "m156.2 51.4h-6.8c-1.3 0-2.3 1.1-2.3 2.3v6.4c0 1.2 1 2.3 2.3 2.3h6.8c1.2 0 2.2-1.1 2.2-2.3v-6.4c0-1.2-1-2.3-2.2-2.3z",
    "fill": "#CECEDE"
  },
  {
    "d": "m96.5 43.6v5h0.9z",
    "fill": "#BF1C21",
    "paint": "shade"
  },
  {
    "d": "m95.4 43.6v10.9h1.1v-13.3h-1.1z",
    "fill": "#BF1C21",
    "paint": "shade"
  },
  {
    "d": "m21.5 10.9c-0.8 0-1.5 0.7-1.5 1.5v3.6c0 1.7 3.1 2.2 3.2 0v-3.6c-0.1-0.8-0.7-1.5-1.7-1.5z",
    "fill": "#CAD1E4"
  },
  {
    "d": "m33.4 11c-0.8 0-1.6 0.6-1.6 1.6v3.4c0 2.2 3.2 2.3 3.3 0.1v-3.5c0-1-0.7-1.6-1.7-1.6z",
    "fill": "#CAD1E4"
  },
  {
    "d": "m45.4 11c-0.9 0-1.6 0.6-1.6 1.6v3.4c0 2.2 3.1 2.4 3.2 0.2v-3.6c0-1-0.6-1.6-1.6-1.6z",
    "fill": "#CAD1E4"
  },
  {
    "d": "m57.5 11c-0.9 0-1.6 0.6-1.6 1.6v3.5c0 2.3 3.1 2.2 3.2 0.1v-3.6c0-1-0.7-1.6-1.6-1.6z",
    "fill": "#CAD1E4"
  },
  {
    "d": "m69.2 11c-1 0-1.6 0.6-1.6 1.6v3.5c0 2.2 3.1 2.3 3.3 0.1v-3.6c0-1-0.8-1.6-1.7-1.6z",
    "fill": "#CAD1E4"
  },
  {
    "d": "m80.7 11c-0.8 0-1.6 0.6-1.6 1.6v3.4c0 2.4 3.1 2.3 3.2 0.2v-3.6c-0.1-1-0.7-1.6-1.6-1.6z",
    "fill": "#CAD1E4"
  },
  {
    "d": "m115.4 18.3h-12c-1.3 0-2.5 0.9-2.6 2.3v13c0 1.3 1.2 2.4 2.1 2.4h12.5c1.5 0.1 2.4-1.1 2.4-2.4v-12.9c0-1.2-0.9-2.4-2.4-2.4z",
    "fill": "#9CDAF7"
  },
  {
    "d": "m100.9 26.4 1-0.1v-3.5c0-1.6 1.5-3.2 3.2-3.2h9.3l0.6-1.3h-11.9c-1 0-2.2 0.9-2.2 2.3v5.8z",
    "fill": "#7CC8EF"
  },
  {
    "d": "m148.1 33.6-4.7-11.6c-0.8-1.9-1.9-3.6-4.4-3.6-2-0.1-14.6-0.1-14.6-0.1-1.3 0-2.2 1.1-2.2 2.3v13c0 1.3 0.9 2.4 2.4 2.4h22c1.3-0.4 1.5-1.6 1.5-2.4z",
    "fill": "#9CDAF7"
  },
  {
    "d": "m143.4 22-0.4-0.9-11.8 14.8 15.3 0.1c1.4 0.1 2.1-1.4 1.6-2.4l-4.7-11.6z",
    "fill": "#7CC8EF"
  },
  {
    "d": "m103.6 36h1.9l12.4-12.9v-1.4l-14.5 14.3z",
    "fill": "#7CC8EF"
  },
  {
    "d": "m115.5 18.4-14.5 14.7 0.5 2.3 15.7-15.8-0.6-1z",
    "fill": "#BBECFB"
  },
  {
    "d": "m134.9 18.7-12.7 14.3 0.9 2.6 2.9 0.4 14.7-16.6-2.6-0.7z",
    "fill": "#BBECFB"
  },
  {
    "d": "m139.1 18.6-6.2-0.2h-8.3c-1.4 0-2.4 1.1-2.4 2.2v0.9c0.3-1.3 1.3-2.1 2.3-2.1h16.1l-1.5-0.8z",
    "fill": "#7CC8EF"
  },
  {
    "d": "m105.2 38.5h-3c-1.8 0-2 2.6 0 2.6h3c1.9 0 1.9-2.6 0-2.6z",
    "fill": "#5C3442"
  }
];

/** The two wheels, each with the centre it spins about. */
export const truckWheels: TruckWheel[] = [
  { ...{"cx":36.75,"cy":63.8,"r":15}, shapes: [
    {
      "d": "m36.7 49.1c-6.6 0-14.3 5.4-14.3 14.1 0 7.7 6 15.3 15.2 15.3 7.5-0.4 13.4-5.5 13.5-15.1 0-8.5-7.2-14.3-14.4-14.3z",
      "fill": "#2B3346"
    },
    {
      "d": "m36.9 55.5c-3.8-0.1-8.1 3-8.2 7.7 0.2 4 3.4 8.4 8.4 8.4 3.8-0.1 7.8-3.2 7.7-8.6-0.2-4.5-3.9-7.5-7.9-7.5z",
      "fill": "#CFD4E4"
    },
    {
      "circle": {
        "cx": 36.8,
        "cy": 63.2,
        "r": 3
      },
      "fill": "#7781A1"
    },
    {
      "circle": {
        "cx": 36.8,
        "cy": 57.9,
        "r": 1.1
      },
      "fill": "#8891AD"
    },
    {
      "circle": {
        "cx": 32.5,
        "cy": 59.6,
        "r": 1.1
      },
      "fill": "#8891AD"
    },
    {
      "circle": {
        "cx": 31.3,
        "cy": 64.1,
        "r": 1.1
      },
      "fill": "#8891AD"
    },
    {
      "circle": {
        "cx": 34,
        "cy": 68.1,
        "r": 1.1
      },
      "fill": "#8891AD"
    },
    {
      "circle": {
        "cx": 39,
        "cy": 68.5,
        "r": 1.1
      },
      "fill": "#8891AD"
    },
    {
      "circle": {
        "cx": 42,
        "cy": 64.4,
        "r": 1.1
      },
      "fill": "#8891AD"
    },
    {
      "circle": {
        "cx": 41,
        "cy": 59.7,
        "r": 1.1
      },
      "fill": "#8891AD"
    }
  ] },
  { ...{"cx":121.4,"cy":63.75,"r":15}, shapes: [
    {
      "d": "m121.4 49c-5.5 0-14.8 4.7-14.8 14.2 0 7.2 5.5 15.3 14.9 15.3 7.4 0 14.7-5.1 14.7-15.5-0.1-8.1-6.7-14-14.8-14z",
      "fill": "#2B3346"
    },
    {
      "d": "m121.5 55.5c-4.5 0-8.4 3.7-8.4 7.7s3.4 8.4 8.4 8.3c3.7 0 8-2.9 8-8.3 0-4.2-3.6-7.7-8-7.7z",
      "fill": "#CAD1E4"
    },
    {
      "circle": {
        "cx": 121.4,
        "cy": 63.2,
        "r": 2.9
      },
      "fill": "#8891AD"
    },
    {
      "ellipse": {
        "cx": 121.5,
        "cy": 57.9,
        "rx": 1.2,
        "ry": 1.2
      },
      "fill": "#7781A1"
    },
    {
      "ellipse": {
        "cx": 117.1,
        "cy": 59.7,
        "rx": 1.1,
        "ry": 1.2
      },
      "fill": "#7781A1"
    },
    {
      "circle": {
        "cx": 115.9,
        "cy": 64.1,
        "r": 1.1
      },
      "fill": "#7781A1"
    },
    {
      "circle": {
        "cx": 118.6,
        "cy": 68.2,
        "r": 1.1
      },
      "fill": "#7781A1"
    },
    {
      "circle": {
        "cx": 123.5,
        "cy": 68.5,
        "r": 1.2
      },
      "fill": "#7781A1"
    },
    {
      "circle": {
        "cx": 126.6,
        "cy": 64.4,
        "r": 1.1
      },
      "fill": "#7781A1"
    },
    {
      "circle": {
        "cx": 125.6,
        "cy": 59.8,
        "r": 1.1
      },
      "fill": "#7781A1"
    }
  ] },
];

/** The plinth under the beacon — always dark. */
export const truckBeaconBase: TruckShape[] = [
    {
      "d": "m110.4 11.8h19.5v-1.8c0-1.1-1.4-2.3-2.8-2.3l-14.2-0.1c-1.1 0-2.5 0.9-2.5 2.3v1.9z",
      "fill": "#252D41"
    },
    {
      "d": "m120.2 7.7h-7.3c-1.1 0-2.5 0.9-2.5 2.3v1.8h9.8v-4.1z",
      "fill": "#2B3346"
    }
  ];

/** The dome that flashes, in the colours the child chose. */
export const truckBeaconDome: TruckShape[] = [
    {
      "d": "m123.2 1.2h-6.4c-1.7 0-3.8 1.5-3.8 3.5v3h13.9v-2.8c0-2.3-2-3.7-3.7-3.7z",
      "fill": "#EB3332"
    },
    {
      "d": "m120.3 1.4v6.3h-7.3v-2.7c0-2 1.7-3.8 3.9-3.8h3.4v0.2z",
      "fill": "#EF3829"
    },
    {
      "d": "m120.7 1.2c1.1 0.5 3.1 1.8 3.2 3.7v2.7h3v-2.7c0.1-1.8-1.3-3.7-3.4-3.7h-2.8z",
      "fill": "#EA2C2F"
    },
    {
      "d": "m114.9 5.9 0.1-0.9c0-1.1 1-2 2-2",
      "stroke": "#F54747",
      "strokeWidth": 1.6341,
      "strokeLinecap": "round"
    }
  ];

/** The door badge: ring and disc stay, the glyph is swapped per decal. */
export const truckDecalRing: TruckShape[] = [
    {
      "d": "m46.9 21c-6.3 0-13.7 5.2-13.8 13.6 0.1 7.1 5.7 13.1 13.8 13.1 7.8 0.1 13.8-6 13.9-12.9 0.1-6.6-6-13.4-13.9-13.8zm0 25.1c-6.3 0-11.9-4.7-12-11.2 0-5.9 5.2-11.4 12-11.4 5.9 0 11.9 4.7 12 11.1 0 6.3-5.3 11.5-12 11.5z",
      "fill": "#BF1C21",
      "paint": "shade"
    }
  ];
export const truckDecalDisc: TruckShape[] = [
    {
      "d": "m46.9 22.1c-5.9 0-12.8 4.6-12.9 12.5 0.1 6.8 5.6 12.3 12.9 12.3 7 0 13-5.5 13.4-12.3-0.4-6.9-6.7-12.5-13.4-12.5z",
      "fill": "#FCF6EC"
    }
  ];
/** The authored flame, used when the child's decal is `flame`. */
export const truckDecalFlame: TruckShape[] = [
    {
      "d": "m46.9 26.3c-2.3 2-6.3 5.3-6.3 9.1s3.6 6.5 6.2 6.7l0.8-0.1c2.5-0.5 5.9-2.9 5.9-6.6 0-4.1-4.6-7.6-6.6-9.1z",
      "fill": "#EF3829"
    },
    {
      "d": "m46.9 34.4c-1.2 1.3-3 2.6-2.9 4.5 0.1 1.5 1.9 3.3 2.9 3.4s3-1.6 3.1-3.5-1.9-3.2-3.1-4.4z",
      "fill": "#FDBA29"
    }
  ];

/** Where the badge sits, so a different decal can be drawn in its place. */
export const TRUCK_DECAL = { cx: 46.9, cy: 34.4, r: 12.4 } as const;
